CREATE TABLE "EDI_Tebra".attachments (
    id serial4 NOT NULL,
    type_id uuid NULL,
    clm_att_path text NULL,
    clm_att_filename text NULL,
    clm_att_datetime timestamp NULL,
    clm_login varchar(500) NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    attachment_type varchar(50) DEFAULT 'claim'::character varying NULL,
    user_id uuid NULL,
    assigned_to_id uuid NULL,
    status varchar(5) DEFAULT 'G'::character varying NOT NULL,
    raw_extracted_data jsonb NULL,
    processed_extracted_data jsonb NULL,
    processed bool DEFAULT false NOT NULL,
    sha varchar(64) NULL,
    extraction_metadata jsonb NULL,
    parent_attachment_id int4 NULL,
    parent_attachment_name text NULL,
    original_file_name text NULL,
    client_id int4 NULL,
    group_id int4 NULL,
    practice_id int4 NULL,
    page_count int4 NULL,
    extracted_files_count int4 NULL,
    rotation_degrees int4 NULL,
    upload_source text NULL,
    associated_claim_dcn varchar(100) NULL,
    claim_creation_response jsonb NULL,
    CONSTRAINT claim_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT attachments_assigned_to_id_fkey FOREIGN KEY (assigned_to_id) REFERENCES rcm.users(id),
    CONSTRAINT attachments_client_id_fkey FOREIGN KEY (client_id) REFERENCES "EDI_Tebra".client(client_id) ON DELETE CASCADE,
    CONSTRAINT attachments_group_id_fkey FOREIGN KEY (group_id) REFERENCES "EDI_Tebra"."group"(id) ON DELETE CASCADE,
    CONSTRAINT attachments_parent_attachment_id_attachments_id_fk FOREIGN KEY (parent_attachment_id) REFERENCES "EDI_Tebra".attachments(id),
    CONSTRAINT attachments_practice_id_fkey FOREIGN KEY (practice_id) REFERENCES "EDI_Tebra".practice(id) ON DELETE CASCADE
);
